version: 1

formatters:
  simpleFormater:
    format: '%(asctime)s - %(levelname)s: %(message)s'
    datefmt: '%Y/%m/%d %H:%M:%S'

handlers:
  error_mail:
    class : smtphandler.SMTPHandler
    formatter: simpleFormater
    level: ERROR
    mailhost: [smtp.gmail.com, 587]
    fromaddr: bot@vertis.com
    toaddrs: [is@vertis.com,]
    subject: Itop-vertis.com Backup process failed
    credentials: [bot@vertis.com, vbudeu*22ets]
    secure: []
  info_mail:
    class : smtphandler.SMTPHandler
    formatter: simpleFormater
    level: INFO
    mailhost: [smtp.gmail.com, 587]
    fromaddr: bot@vertis.com
    toaddrs: [is@vertis.com,]
    subject: Itop-vertis.com Backup OK
    credentials: [bot@vertis.com, vbudeu*22ets]
    secure: []

loggers:
  error:
    level: ERROR
    handlers: [error_mail]

  ok:
    level: INFO
    handlers: [info_mail]
