version: '3'

volumes:
  mysql:
  itop:


services:
  mysql:
    hostname: mysql
    image: ${REGISTRY_URL}/${COMPOSE_PROJECT_NAME}-mysql:${VERSION}
    env_file: .env
    command: ["mysqld"]
    volumes:
      - mysql:/var/lib/mysql
      - "./.secret.env:/.secret.env"
    ports:
      - "127.0.0.1:3306:3306"

  itop:
    image: ${REGISTRY_URL}/${COMPOSE_PROJECT_NAME}-itop:${VERSION}
    command: ["itop"]
    env_file: .env
    volumes:
      - itop:/var/www/html
      - ./.files/certificate.crt:/certificate.crt
      - ./.files/certificate.key:/certificate.key
      - "./.secret.env:/.secret.env"
    ports:
      - 4430:443


  curator:
    image: ${REGISTRY_URL}/${COMPOSE_PROJECT_NAME}-mysql:${VERSION}
    env_file: .env
    depends_on: ["mysql"]
    volumes:
      - ./backup/:/backup/
      - "./.secret.env:/.secret.env"
    command: ["python3", "/task.py"]
