version: '3'

volumes:
  itop-data-volume:
  itop-conf-volume:
  itop-log-volume:
  itop-env-production-volume:
  itop-backup-volume:


services:
  mysql:
    hostname: mysql
    image: ${REGISTRY_URL}/${COMPOSE_PROJECT_NAME}-mysql:${VERSION}
    env_file: .env
    command: ["mysqld"]
    volumes:
      - itop-data-volume:/var/lib/mysql
      - "./.secret.env:/.secret.env"
    ports:
      - "127.0.0.1:3306:3306"

  itop:
    image: ${REGISTRY_URL}/${COMPOSE_PROJECT_NAME}-itop:${VERSION}
    command: ["bash", "run.sh"]
    env_file: .env
    volumes:
      - itop-env-production-volume:/var/www/html/env-production
      - itop-conf-volume:/var/www/html/conf
      - itop-log-volume:/var/www/html/log
      - itop-backup-volume:/var/www/html/data
      - ./.files/certificate.crt:/certificate.crt
      - ./.files/certificate.key:/certificate.key
      - "./.secret.env:/.secret.env"
    ports:
      - 4430:443
      - 80:80

  curator:
    image: ${REGISTRY_URL}/${COMPOSE_PROJECT_NAME}-mysql:${VERSION}
    env_file: .env
    depends_on: ["mysql"]
    volumes:
      - ./backup/:/backup/
<<<<<<< HEAD
      - "./.secret.env:/.secret.env"
=======
>>>>>>> 79032b8abf5915118813de20607fe77349b14764
    command: ["python3", "/task.py"]
