version: '3'

volumes:
  itop-data-volume:
  itop-conf-volume:
  itop-log-volume:
  itop-env-production-volume:
  itop-backup-volume:


services:
  mysql:
    hostname: mysql
    image: mysql:5.7.26
    env_file: .env
    volumes:
      - itop-data-volume:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: "1"
    restart: always
    ports:
     - 3305:80

  itop:
    image: ${REGISTRY_URL}/${COMPOSE_PROJECT_NAME}-${VERSION}:latest
    command: ["bash", "run.sh"]
    env_file: .env
    volumes:
      - itop-env-production-volume:/var/www/html/env-production
      - itop-conf-volume:/var/www/html/conf
      - itop-log-volume:/var/www/html/log
      - itop-backup-volume:/var/www/html/data
      - ./.files/certificate.crt:/certificate.crt
      - ./.files/certificate.key:/certificate.key
    ports:
      - 4430:443
      - 80:80
