version: '2'

volumes:
  itop-data-volume:
    driver: local
  itop-conf-volume:
    driver: local
  itop-log-volume:
    driver: local
  itop-env-production-volume:
    driver: local
  itop-backup-volume:
    driver: local


services:
  mysql:
    hostname: mysql
    image: vertis-docker-registry:5000/itop-mysql:latest
    env_file: .secret
    environment:
      MYSQL_DATABASE: itop
      MYSQL_USER: itop
      HOST: localhost
      LDAP_USER: itop
    volumes:
      - itop-data-volume:/var/lib/mysql
      # - ../../docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
        PMA_ARBITRARY: "1"
      restart: always
      ports:
       - 3305:80

  itop:
    image: vertis-docker-registry:5000/itop-itop:latest
    command: ["bash", "run.sh"]
    env_file: .secret
        environment:
          MYSQL_DATABASE: itop
          MYSQL_USER: itop
          HOST: localhost
          LDAP_USER: itop
    volumes:
      - itop-env-production-volume:/var/www/html/env-production
      - itop-conf-volume:/var/www/html/conf
      - itop-log-volume:/var/www/html/log
      - itop-backup-volume:/var/www/html/data
      - ./localhost.crt:/certificate.crt
      - ./localhost.key:/certificate.key
      - ./docker/itop/apache_conf/dev_000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 4430:443
      - 80:80
