version: '2'

volumes:
  itop-data-volume:
    driver: local
  itop-conf-volume:
    driver: local
  itop-log-volume:
    driver: local
  itop-env-production-volume:
    driver: local
  itop-backup-volume:
    driver: local


services:
  mysql:
    hostname: mysql
    container_name: itop_mysql
    image: vertis-docker-registry:5000/itop-mysql:latest
    env_file: .secret
    volumes:
      - itop-data-volume:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: itop_phpmyadmin
      environment:
        PMA_ARBITRARY: "1"
      restart: always
      ports:
       - 3305:80

  itop:
    image: vertis-docker-registry:5000/itop-itop:latest
    container_name: itop_itop
    command: ["bash", "run.sh"]
    env_file: .secret
    volumes:
      - itop-env-production-volume:/var/www/html/env-production
      - itop-conf-volume:/var/www/html/conf
      - itop-log-volume:/var/www/html/log
      - itop-backup-volume:/var/www/html/data
      - ./itop.vertis.com.crt:/certificate.crt
      - ./itop.vertis.com.key:/certificate.key
    ports:
      - 4430:443
