version: '2'

volumes:
  itop-data-volume:
    driver: local

services:
  mysql:
    hostname: mysql
    image: mysql
    env_file: .secret
    volumes:
      - itop-data-volume:/var/lib/mysql
      - ../../docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
        PMA_ARBITRARY: "1"
      restart: always
      ports:
       - 3306:80

  itop:
    image: itop
    command: ["bash", "run.sh"]
    env_file: .secret
    volumes:
      - ../../core/env-production:/var/www/html/env-production
      - ./conf:/var/www/html/conf
      - ../../core/log:/var/www/html/log
      - ../../core/data:/var/www/html/data
      - ../../core/extensions:/var/www/html/extensions
      - ./localhost.crt:/certificate.crt
      - ./localhost.key:/certificate.key
      - ../../docker/itop/apache_conf/dev_000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 4430:443
