<?php
//
// File generated on 2016-11-02T15:09:34+0100
// Please do not edit manually
//
MetaModel::IncludeModule('env-production/core/main.php');
MetaModel::IncludeModule('env-production/authent-external/model.authent-external.php');
MetaModel::IncludeModule('env-production/authent-ldap/model.authent-ldap.php');
MetaModel::IncludeModule('env-production/authent-local/model.authent-local.php');
MetaModel::IncludeModule('env-production/combodo-email-synchro/model.email-synchro.php');
MetaModel::IncludeModule('env-production/combodo-email-synchro/mailinbox.class.inc.php');
MetaModel::IncludeModule('env-production/combodo-email-synchro/emailprocessor.class.inc.php');
MetaModel::IncludeModule('env-production/combodo-email-synchro/emailbackgroundprocess.class.inc.php');
MetaModel::IncludeModule('env-production/combodo-email-synchro/trigger.class.inc.php');
MetaModel::IncludeModule('env-production/email-reply/main.email-reply.php');
MetaModel::IncludeModule('env-production/itop-attachments/model.itop-attachments.php');
MetaModel::IncludeModule('env-production/itop-attachments/main.attachments.php');
MetaModel::IncludeModule('env-production/itop-backup/main.itop-backup.php');
MetaModel::IncludeModule('env-production/itop-config-mgmt/model.itop-config-mgmt.php');
MetaModel::IncludeModule('env-production/itop-config-mgmt/main.itop-config-mgmt.php');
MetaModel::IncludeModule('env-production/itop-config/main.itop-config.php');
MetaModel::IncludeModule('env-production/itop-datacenter-mgmt/model.itop-datacenter-mgmt.php');
MetaModel::IncludeModule('env-production/itop-endusers-devices/model.itop-endusers-devices.php');
MetaModel::IncludeModule('env-production/itop-portal-base/portal/src/entities/abstractbrick.class.inc.php');
MetaModel::IncludeModule('env-production/itop-portal-base/portal/src/entities/portalbrick.class.inc.php');
MetaModel::IncludeModule('env-production/itop-portal-base/portal/src/controllers/abstractcontroller.class.inc.php');
MetaModel::IncludeModule('env-production/itop-portal-base/portal/src/controllers/brickcontroller.class.inc.php');
MetaModel::IncludeModule('env-production/itop-portal-base/portal/src/routers/abstractrouter.class.inc.php');
MetaModel::IncludeModule('env-production/itop-portal/main.itop-portal.php');
MetaModel::IncludeModule('env-production/itop-profiles-itil/model.itop-profiles-itil.php');
MetaModel::IncludeModule('env-production/itop-sla-computation/main.itop-sla-computation.php');
MetaModel::IncludeModule('env-production/itop-standard-email-synchro/mailinboxstandard.class.inc.php');
MetaModel::IncludeModule('env-production/itop-standard-email-synchro/model.itop-standard-email-synchro.php');
MetaModel::IncludeModule('env-production/itop-storage-mgmt/model.itop-storage-mgmt.php');
MetaModel::IncludeModule('env-production/itop-tickets/main.itop-tickets.php');
MetaModel::IncludeModule('env-production/itop-tickets/model.itop-tickets.php');
MetaModel::IncludeModule('env-production/itop-virtualization-mgmt/model.itop-virtualization-mgmt.php');
MetaModel::IncludeModule('env-production/itop-welcome-itil/main.itop-welcome-itil.php');
MetaModel::IncludeModule('env-production/itop-welcome-itil/model.itop-welcome-itil.php');
MetaModel::IncludeModule('env-production/itop-bridge-virtualization-storage/model.itop-bridge-virtualization-storage.php');
MetaModel::IncludeModule('env-production/itop-change-mgmt-itil/model.itop-change-mgmt-itil.php');
MetaModel::IncludeModule('env-production/itop-incident-mgmt-itil/model.itop-incident-mgmt-itil.php');
MetaModel::IncludeModule('env-production/itop-knownerror-mgmt/model.itop-knownerror-mgmt.php');
MetaModel::IncludeModule('env-production/itop-problem-mgmt/model.itop-problem-mgmt.php');
MetaModel::IncludeModule('env-production/itop-request-mgmt-itil/model.itop-request-mgmt-itil.php');
MetaModel::IncludeModule('env-production/itop-request-mgmt-itil/main.itop-request-mgmt-itil.php');
MetaModel::IncludeModule('env-production/itop-service-mgmt/model.itop-service-mgmt.php');